### ISSUE TITLE
lib/index.js is outdated

### ISSUE THREAD

**Issue by teohhanhui** [cyclejs/cycle-fetch-driver#7]
Is the `prepublish` script not working properly?

**Comment by secobarbital** [comment]
It should be, but the problem is I don't have access to the @cycle namespace on npm so staltz has to publish. I am now making changes on my own fork to send over as pull requests.

Currently besides the README changes I have also eliminated the mess of gitignore/npmignore files just to keep the `lib` directory present but empty, and instead opted to exclude the entire directory and create it prepublish.

Let me pull them over so you can work off of those.

**Comment by secobarbital** [comment]
There. No more `lib/index.js`. It will only get created `prepublish`.
